FROM jenkins/jenkins:lts
MAINTAINER Gayatri S Ajith <gayatri@schogini.com>

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
USER root
RUN apt-get update
RUN apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN echo 'deb https://apt.dockerproject.org/repo debian-stretch main' >> /etc/apt/sources.list
RUN apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
RUN apt-get update
RUN apt-get install -y docker-engine
RUN usermod -aG docker jenkins
RUN service docker stop
RUN service docker start
